name: Build, Scan and Push Docker Image to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: ecr-lab-app
  ECR_REGISTRY: 696223520711.dkr.ecr.eu-central-1.amazonaws.com

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .

      - name: Scan IaC and config files with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ecr-lab-app:latest
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          
  deploy-to-minikube:
    needs: build-scan-and-push
    runs-on: self-hosted

    steps:
      - name: Refresh ECR pull secret
        run: |
          ECR_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)

          kubectl create secret docker-registry ecr-secret \
            --docker-server=$ECR_REGISTRY \
            --docker-username=AWS \
            --docker-password="$ECR_PASSWORD" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy image to Minikube
        run: |
          kubectl set image deployment/ecr-lab-app \
            ecr-lab-app=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

          kubectl rollout status deployment/ecr-lab-app

      - name: Show running image
        run: |
          kubectl get deployment ecr-lab-app -o jsonpath='{.spec.template.spec.containers[0].image}'
          echo